[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
gas_reports = ["*"]

solc_version='0.8.27'
optimizer = true
optimizer-runs = 200
via_ir = true

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
localhost = "${LOCALHOST_RPC_URL}"

[etherscan]
sepolia = { key = "${SEPOLIA_ETHERSCAN_API_KEY}" }